/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContentType = IDL.Variant({
  'Blog' : IDL.Null,
  'Page' : IDL.Null,
  'Resource' : IDL.Null,
});
export const ContentStatus = IDL.Variant({
  'Draft' : IDL.Null,
  'Published' : IDL.Null,
});
export const ContentId = IDL.Text;
export const Timestamp = IDL.Int;
export const ContentItem = IDL.Record({
  'id' : ContentId,
  'status' : ContentStatus,
  'title' : IDL.Text,
  'contentType' : ContentType,
  'createdAt' : Timestamp,
  'author' : IDL.Text,
  'updatedAt' : Timestamp,
});
export const UserRole = IDL.Variant({
  'Viewer' : IDL.Null,
  'Editor' : IDL.Null,
  'Admin' : IDL.Null,
});
export const UserStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const UserId = IDL.Text;
export const User = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'joinDate' : Timestamp,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const Metrics = IDL.Record({
  'sevenDayChange' : IDL.Float64,
  'contentItems' : IDL.Nat,
  'activeSessions' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const SearchResults = IDL.Record({
  'userResults' : IDL.Vec(User),
  'contentResults' : IDL.Vec(ContentItem),
});

export const idlService = IDL.Service({
  'createContent' : IDL.Func(
      [IDL.Text, ContentType, IDL.Text, ContentStatus],
      [ContentItem],
      [],
    ),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, UserRole, UserStatus],
      [User],
      [],
    ),
  'deleteContent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getContent' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
  'getContentItem' : IDL.Func([IDL.Text], [IDL.Opt(ContentItem)], ['query']),
  'getMetrics' : IDL.Func([], [Metrics], ['query']),
  'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'searchAll' : IDL.Func([IDL.Text], [SearchResults], ['query']),
  'togglePublish' : IDL.Func([IDL.Text], [IDL.Opt(ContentItem)], []),
  'updateContent' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(ContentType),
        IDL.Opt(IDL.Text),
        IDL.Opt(ContentStatus),
      ],
      [IDL.Opt(ContentItem)],
      [],
    ),
  'updateUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(UserRole),
        IDL.Opt(UserStatus),
      ],
      [IDL.Opt(User)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContentType = IDL.Variant({
    'Blog' : IDL.Null,
    'Page' : IDL.Null,
    'Resource' : IDL.Null,
  });
  const ContentStatus = IDL.Variant({
    'Draft' : IDL.Null,
    'Published' : IDL.Null,
  });
  const ContentId = IDL.Text;
  const Timestamp = IDL.Int;
  const ContentItem = IDL.Record({
    'id' : ContentId,
    'status' : ContentStatus,
    'title' : IDL.Text,
    'contentType' : ContentType,
    'createdAt' : Timestamp,
    'author' : IDL.Text,
    'updatedAt' : Timestamp,
  });
  const UserRole = IDL.Variant({
    'Viewer' : IDL.Null,
    'Editor' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const UserStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
  });
  const UserId = IDL.Text;
  const User = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'joinDate' : Timestamp,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const Metrics = IDL.Record({
    'sevenDayChange' : IDL.Float64,
    'contentItems' : IDL.Nat,
    'activeSessions' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const SearchResults = IDL.Record({
    'userResults' : IDL.Vec(User),
    'contentResults' : IDL.Vec(ContentItem),
  });
  
  return IDL.Service({
    'createContent' : IDL.Func(
        [IDL.Text, ContentType, IDL.Text, ContentStatus],
        [ContentItem],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, UserRole, UserStatus],
        [User],
        [],
      ),
    'deleteContent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteUser' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getContent' : IDL.Func([], [IDL.Vec(ContentItem)], ['query']),
    'getContentItem' : IDL.Func([IDL.Text], [IDL.Opt(ContentItem)], ['query']),
    'getMetrics' : IDL.Func([], [Metrics], ['query']),
    'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'searchAll' : IDL.Func([IDL.Text], [SearchResults], ['query']),
    'togglePublish' : IDL.Func([IDL.Text], [IDL.Opt(ContentItem)], []),
    'updateContent' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(ContentType),
          IDL.Opt(IDL.Text),
          IDL.Opt(ContentStatus),
        ],
        [IDL.Opt(ContentItem)],
        [],
      ),
    'updateUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(UserRole),
          IDL.Opt(UserStatus),
        ],
        [IDL.Opt(User)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };