/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContentId = string;
export interface ContentItem {
  'id' : ContentId,
  'status' : ContentStatus,
  'title' : string,
  'contentType' : ContentType,
  'createdAt' : Timestamp,
  'author' : string,
  'updatedAt' : Timestamp,
}
export type ContentStatus = { 'Draft' : null } |
  { 'Published' : null };
export type ContentType = { 'Blog' : null } |
  { 'Page' : null } |
  { 'Resource' : null };
export interface Metrics {
  'sevenDayChange' : number,
  'contentItems' : bigint,
  'activeSessions' : bigint,
  'totalUsers' : bigint,
}
export interface SearchResults {
  'userResults' : Array<User>,
  'contentResults' : Array<ContentItem>,
}
export type Timestamp = bigint;
export interface User {
  'id' : UserId,
  'status' : UserStatus,
  'joinDate' : Timestamp,
  'name' : string,
  'role' : UserRole,
  'email' : string,
}
export type UserId = string;
export type UserRole = { 'Viewer' : null } |
  { 'Editor' : null } |
  { 'Admin' : null };
export type UserStatus = { 'Inactive' : null } |
  { 'Active' : null };
export interface _SERVICE {
  'createContent' : ActorMethod<
    [string, ContentType, string, ContentStatus],
    ContentItem
  >,
  'createUser' : ActorMethod<[string, string, UserRole, UserStatus], User>,
  'deleteContent' : ActorMethod<[string], boolean>,
  'deleteUser' : ActorMethod<[string], boolean>,
  'getContent' : ActorMethod<[], Array<ContentItem>>,
  'getContentItem' : ActorMethod<[string], [] | [ContentItem]>,
  'getMetrics' : ActorMethod<[], Metrics>,
  'getUser' : ActorMethod<[string], [] | [User]>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'searchAll' : ActorMethod<[string], SearchResults>,
  'togglePublish' : ActorMethod<[string], [] | [ContentItem]>,
  'updateContent' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [ContentType],
      [] | [string],
      [] | [ContentStatus],
    ],
    [] | [ContentItem]
  >,
  'updateUser' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [UserRole], [] | [UserStatus]],
    [] | [User]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];