/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = string;
export type Timestamp = bigint;
export type ContentId = string;
export interface User {
    id: UserId;
    status: UserStatus;
    joinDate: Timestamp;
    name: string;
    role: UserRole;
    email: string;
}
export interface ContentItem {
    id: ContentId;
    status: ContentStatus;
    title: string;
    contentType: ContentType;
    createdAt: Timestamp;
    author: string;
    updatedAt: Timestamp;
}
export interface SearchResults {
    userResults: Array<User>;
    contentResults: Array<ContentItem>;
}
export interface Metrics {
    sevenDayChange: number;
    contentItems: bigint;
    activeSessions: bigint;
    totalUsers: bigint;
}
export enum ContentStatus {
    Draft = "Draft",
    Published = "Published"
}
export enum ContentType {
    Blog = "Blog",
    Page = "Page",
    Resource = "Resource"
}
export enum UserRole {
    Viewer = "Viewer",
    Editor = "Editor",
    Admin = "Admin"
}
export enum UserStatus {
    Inactive = "Inactive",
    Active = "Active"
}
export interface backendInterface {
    createContent(title: string, contentType: ContentType, author: string, status: ContentStatus): Promise<ContentItem>;
    createUser(name: string, email: string, role: UserRole, status: UserStatus): Promise<User>;
    deleteContent(id: string): Promise<boolean>;
    deleteUser(id: string): Promise<boolean>;
    getContent(): Promise<Array<ContentItem>>;
    getContentItem(id: string): Promise<ContentItem | null>;
    getMetrics(): Promise<Metrics>;
    getUser(id: string): Promise<User | null>;
    getUsers(): Promise<Array<User>>;
    searchAll(searchTerm: string): Promise<SearchResults>;
    togglePublish(id: string): Promise<ContentItem | null>;
    updateContent(id: string, title: string | null, contentType: ContentType | null, author: string | null, status: ContentStatus | null): Promise<ContentItem | null>;
    updateUser(id: string, name: string | null, email: string | null, role: UserRole | null, status: UserStatus | null): Promise<User | null>;
}
import type { ContentId as _ContentId, ContentItem as _ContentItem, ContentStatus as _ContentStatus, ContentType as _ContentType, SearchResults as _SearchResults, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserRole as _UserRole, UserStatus as _UserStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createContent(arg0: string, arg1: ContentType, arg2: string, arg3: ContentStatus): Promise<ContentItem> {
        if (this.processError) {
            try {
                const result = await this.actor.createContent(arg0, to_candid_ContentType_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_ContentStatus_n3(this._uploadFile, this._downloadFile, arg3));
                return from_candid_ContentItem_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createContent(arg0, to_candid_ContentType_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_ContentStatus_n3(this._uploadFile, this._downloadFile, arg3));
            return from_candid_ContentItem_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: string, arg1: string, arg2: UserRole, arg3: UserStatus): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg2), to_candid_UserStatus_n13(this._uploadFile, this._downloadFile, arg3));
                return from_candid_User_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg2), to_candid_UserStatus_n13(this._uploadFile, this._downloadFile, arg3));
            return from_candid_User_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteContent(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContent(arg0);
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getContent(): Promise<Array<ContentItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContent();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContent();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContentItem(arg0: string): Promise<ContentItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContentItem(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContentItem(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetrics(): Promise<Metrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics();
            return result;
        }
    }
    async getUser(arg0: string): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchAll(arg0: string): Promise<SearchResults> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAll(arg0);
                return from_candid_SearchResults_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAll(arg0);
            return from_candid_SearchResults_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async togglePublish(arg0: string): Promise<ContentItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePublish(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePublish(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateContent(arg0: string, arg1: string | null, arg2: ContentType | null, arg3: string | null, arg4: ContentStatus | null): Promise<ContentItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContent(arg0, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg4));
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContent(arg0, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n28(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg4));
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: string, arg1: string | null, arg2: string | null, arg3: UserRole | null, arg4: UserStatus | null): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg4));
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, to_candid_opt_n27(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n27(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg4));
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ContentItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentItem): ContentItem {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ContentStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentStatus): ContentStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ContentType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_SearchResults_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchResults): SearchResults {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_User_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContentItem]): ContentItem | null {
    return value.length === 0 ? null : from_candid_ContentItem_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    status: _UserStatus;
    joinDate: _Timestamp;
    name: string;
    role: _UserRole;
    email: string;
}): {
    id: UserId;
    status: UserStatus;
    joinDate: Timestamp;
    name: string;
    role: UserRole;
    email: string;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n17(_uploadFile, _downloadFile, value.status),
        joinDate: value.joinDate,
        name: value.name,
        role: from_candid_UserRole_n19(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userResults: Array<_User>;
    contentResults: Array<_ContentItem>;
}): {
    userResults: Array<User>;
    contentResults: Array<ContentItem>;
} {
    return {
        userResults: from_candid_vec_n24(_uploadFile, _downloadFile, value.userResults),
        contentResults: from_candid_vec_n21(_uploadFile, _downloadFile, value.contentResults)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ContentId;
    status: _ContentStatus;
    title: string;
    contentType: _ContentType;
    createdAt: _Timestamp;
    author: string;
    updatedAt: _Timestamp;
}): {
    id: ContentId;
    status: ContentStatus;
    title: string;
    contentType: ContentType;
    createdAt: Timestamp;
    author: string;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_ContentStatus_n7(_uploadFile, _downloadFile, value.status),
        title: value.title,
        contentType: from_candid_ContentType_n9(_uploadFile, _downloadFile, value.contentType),
        createdAt: value.createdAt,
        author: value.author,
        updatedAt: value.updatedAt
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Blog: null;
} | {
    Page: null;
} | {
    Resource: null;
}): ContentType {
    return "Blog" in value ? ContentType.Blog : "Page" in value ? ContentType.Page : "Resource" in value ? ContentType.Resource : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
}): UserStatus {
    return "Inactive" in value ? UserStatus.Inactive : "Active" in value ? UserStatus.Active : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Viewer: null;
} | {
    Editor: null;
} | {
    Admin: null;
}): UserRole {
    return "Viewer" in value ? UserRole.Viewer : "Editor" in value ? UserRole.Editor : "Admin" in value ? UserRole.Admin : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Draft: null;
} | {
    Published: null;
}): ContentStatus {
    return "Draft" in value ? ContentStatus.Draft : "Published" in value ? ContentStatus.Published : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContentItem>): Array<ContentItem> {
    return value.map((x)=>from_candid_ContentItem_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n15(_uploadFile, _downloadFile, x));
}
function to_candid_ContentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentStatus): _ContentStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ContentType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): _UserStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType | null): [] | [_ContentType] {
    return value === null ? candid_none() : candid_some(to_candid_ContentType_n1(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentStatus | null): [] | [_ContentStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ContentStatus_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole | null): [] | [_UserRole] {
    return value === null ? candid_none() : candid_some(to_candid_UserRole_n11(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus | null): [] | [_UserStatus] {
    return value === null ? candid_none() : candid_some(to_candid_UserStatus_n13(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    Viewer: null;
} | {
    Editor: null;
} | {
    Admin: null;
} {
    return value == UserRole.Viewer ? {
        Viewer: null
    } : value == UserRole.Editor ? {
        Editor: null
    } : value == UserRole.Admin ? {
        Admin: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    Inactive: null;
} | {
    Active: null;
} {
    return value == UserStatus.Inactive ? {
        Inactive: null
    } : value == UserStatus.Active ? {
        Active: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    Blog: null;
} | {
    Page: null;
} | {
    Resource: null;
} {
    return value == ContentType.Blog ? {
        Blog: null
    } : value == ContentType.Page ? {
        Page: null
    } : value == ContentType.Resource ? {
        Resource: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentStatus): {
    Draft: null;
} | {
    Published: null;
} {
    return value == ContentStatus.Draft ? {
        Draft: null
    } : value == ContentStatus.Published ? {
        Published: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
